name: mapbox_turn_by_turn
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_mapbox_navigation: ^0.0.26 
  shared_preferences: ^2.0.13
  flutter_native_splash: ^2.0.4
  location: ^4.3.0
  #google_fonts: ^6.1.0
  flutter_dotenv: ^5.0.2
  dio: ^4.0.4 
  mapbox_gl: ^0.15.0
  intl: ^0.17.0
  flutter_rating_bar: ^4.0.0
  carousel_slider: ^4.2.1
  http: ^1.1.0
  custom_clippers: ^2.0.0
  flutter_otp_text_field: ^1.1.1
  otp_text_field: ^1.1.3
  google_fonts: ^6.1.0
  camera_android: ^0.10.8+13
  provider: ^6.0.4
  flutter_flow_chart: ^1.0.0
  auto_size_text: 3.0.0
  cached_network_image: 3.2.1
  flutter_animate: 4.1.1+1
  #flutter_cache_manager: 3.3.0
  font_awesome_flutter: 10.1.0
  from_css_color: 2.0.0
  go_router: 7.1.1
  json_path: 0.6.2
  page_transition: 2.0.4
  path_provider: 2.0.14
  path_provider_android: 2.0.25
  path_provider_foundation: 2.2.2
  path_provider_platform_interface: 2.0.6
  shared_preferences_android: 2.1.0
  shared_preferences_ios: 2.1.1
  shared_preferences_platform_interface: 2.2.0
  shared_preferences_web: 2.1.0
  sqflite: 2.2.6
  timeago: 3.2.2
  url_launcher: 6.1.10
  url_launcher_android: 6.0.27
  url_launcher_ios: 6.1.4
  url_launcher_platform_interface: 2.1.2
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.10
  socket_io_client: ^2.0.3+1
  dotenv: ^4.2.0
  bcrypt: ^1.1.3
  flutter_polyline_points: ^2.0.0
  google_maps_flutter: ^2.5.3
  flutter_carousel_slider: ^1.1.0
  # google_language_fonts: ^2.0.0

# dependency_overrides:
#   com.mapbox.common:common: '23.3.2'
#   com.mapbox.mapboxsdk:mapbox-android-core: '5.0.0'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2

flutter_native_splash:
  color: "#3F51B5"

flutter_icons:
  android: "logo_ncc"
  ios: true
  image_path: "assets/icon/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icon/
    - assets/image/
    - assets/config/
